=head1 NAME

MooX::Failover - Instantiate Moo classes with failover

=head1 VERSION

v0.2.0_01

=head1 SYNOPSIS

  # In your class:

  package MyClass;

  use Moo;
  use MooX::Failover;

  has 'attr' => ( ... );

  # after attributes are defined:

  failover_to 'OtherClass';

  ...

  # When using the class

  my $obj = MyClass->new( %args );

  # If %args contains missing or invalid values or new otherwise
  # fails, then $obj will be of type "OtherClass".

=head1 INSTALLATION

See
L<How to install CPAN modules|http://www.cpan.org/modules/INSTALL.html>.

=head2 Required Modules

This distribution requires Perl v5.10.0.

This distribution requires the following modules:

=over 4

=item * L<Class::Load> (version 0.20)

=item * L<Moo>

=item * L<Sub::Defer>

=item * L<Sub::Quote>

=item * L<Test::Most>

=back

This distribution recommends the following modules:

=over 4

=item * L<Class::Load::XS>

=back

=head1 RECENT CHANGES

=head2 Enhancements

=over 4

=item * 

Significant optimizations at the expense of incompatability.

=item * 

Added the ability to use an alternative name of the constructor for the failover class.

=item * 

Arguments for the constructor can be a hash reference, array reference or scalar.

=item * 

Added the ability to save the name of the class that triggered to error.

=back

=head2 Incompatability

=over 4

=item * 

Rewrote the interface entirely, so that the failover is specified as part of the class definition. See the POD for details.

=back

=head2 Other Changes

=over 4

=item * 

Added missing MANIFEST.SKIP and removed dist.ini from distribution.

=item * 

Added an example using Web::Machine.

=back

See the F<Changes> file for a longer revision history.

=head1 DESCRIPTION

This role provides constructor failover for L<Moo> classes.

If a class cannot be instantiated because of invalid arguments
(perhaps from an untrusted source), then instead it returns the
failover class (passing the same arguments to that class).

It is roughly equivalent to using

  my $obj = eval { MyClass->new(%args) //
     OtherClass->new( %args, error => $@ );

This allows for cleaner design, by not forcing you to duplicate type
checking for class parameters.

A use case for this module is for instantiating
L<Web::Machine::Resource> objects, where a resource class's attributes
correspond to URL arguments.  A type failure would normally cause an
internal serror error (HTTP 500).  Using L<MooX::Failover>, we can
return a different resource object that examines the error, and
returns a more appropriate error code, e.g. bad request (HTTP 400).

=head1 SEE ALSO

L<MooseX::Failover>

=head1 AUTHOR

Robert Rothenberg C<<rrwo@thermeon.com>>

=head1 Acknowledgements

=over

=item Thermeon Europe.

=item Piers Cawley.

=back

=head1 COPYRIGHT

Copyright 2014 Thermeon Europe.

This library is free software; you can redistribute it and/or modify
it under the same terms as Perl itself.

This program is distributed in the hope that it will be useful, but
without any warranty; without even the implied warranty of
merchantability or fitness for a particular purpose.

